"""
CURANIQ — Medical Evidence Operating System
Layer 4: Adversarial LLM Cross-Verification (L4-12) + Confidence Scorer (L4-13)

L4-12 — Adversarial LLM Cross-Verification (Jury Protocol):
'After the Constrained Generator produces draft claims from evidence, this module
runs adversarial verification. The verifier NEVER generates alternative answers —
it only critiques. Critiquing is more reliable than generating.'

Verification flow:
1. PRIMARY path — Claude generates structured claims from evidence IDs
2. VERIFIER path — GPT-4o receives SAME evidence + Claude's claims
   → Asked ONLY to critique: 'Does each claim faithfully represent the evidence?'
   → Flag: distortions, omissions, scope misapplications, unsupported inferences
3. TIE-BREAKING — if verifier flags → NLI model (SciFact/MedNLI) breaks tie
   (a) NLI agrees with verifier → claim SUPPRESSED
   (b) NLI agrees with primary → claim PASSES with uncertainty marker
4. THRESHOLD — if >30% of claims in high-risk query flagged → REFUSE + escalate

L4-13 — Confidence Scoring & Uncertainty Quantifier:
Full composite score = weighted average of:
(a) NLI entailment score (0.0-1.0)
(b) Cross-LLM agreement from L4-12
(c) Evidence quality per Oxford CEBM
(d) Evidence recency
(e) Source count
"""

from __future__ import annotations

import json
import logging
from datetime import datetime, timezone
from typing import Optional

import aiohttp

from curaniq.models.claims import (
    AtomicClaim,
    ClaimContract,
    ClaimType,
    ClaimVerdict,
    VerifierDecision,
    HIGH_RISK_CLAIM_TYPES,
)
from curaniq.models.evidence import EvidenceChunk, EvidencePack

logger = logging.getLogger(__name__)


# ─────────────────────────────────────────────────────────────────────────────
# ADVERSARIAL VERIFIER PROMPT
# GPT-4o receives this — it critiques ONLY, never generates
# ─────────────────────────────────────────────────────────────────────────────

VERIFIER_SYSTEM_PROMPT = """You are a clinical evidence verifier. Your ONLY role is to critique clinical claims.

You will receive:
1. Evidence snippets (the ground truth)
2. Clinical claims generated by another AI from that evidence

Your task: For each claim, determine if it FAITHFULLY represents the evidence.

Flag a claim ONLY if it exhibits:
- DISTORTED: The claim changes numbers, probabilities, or effect sizes from the evidence
- OMISSION: Critical safety information (contraindications, warnings) from the evidence is missing
- SCOPE_MISS: The claim applies evidence to a different population than studied (e.g., adults→children, normal renal function→CKD)
- UNSUPPORTED: The claim makes an inference not directly supported by the provided evidence
- FABRICATED: The claim references facts not present in any provided evidence snippet

Do NOT generate alternative claims. Do NOT add information. ONLY critique what is present.

If a claim faithfully represents its evidence snippet: mark it FAITHFUL.

Output ONLY valid JSON. No preamble, no explanation outside JSON.

Format:
{
  "verifications": [
    {
      "claim_id": "<id>",
      "decision": "FAITHFUL|DISTORTED|OMISSION|SCOPE_MISS|UNSUPPORTED|FABRICATED",
      "critique": "<brief factual critique if not FAITHFUL, else null>"
    }
  ]
}"""

VERIFIER_USER_TEMPLATE = """EVIDENCE SNIPPETS:
{evidence_context}

CLAIMS TO VERIFY:
{claims_json}

Verify each claim against its evidence snippet. Output JSON only."""


# ─────────────────────────────────────────────────────────────────────────────
# ADVERSARIAL LLM JURY — L4-12
# ─────────────────────────────────────────────────────────────────────────────

class AdversarialLLMJury:
    """
    L4-12: Adversarial LLM Cross-Verification Protocol.
    
    'The probability of both [models] hallucinating the same wrong claim
    from the same evidence is extremely low.' — CURANIQ v3.6
    
    Cost: ~2x LLM cost per query (acceptable for medical safety)
    Latency: +1-2 seconds (verifier runs in parallel with primary)
    """

    def __init__(
        self,
        primary_api_key: Optional[str] = None,
        verifier_api_key: Optional[str] = None,
        nli_endpoint: str = "http://localhost:8100/entailment",
        high_risk_flag_threshold: float = 0.30,  # >30% flagged → REFUSE
        verifier_model: str = "gpt-4o",
        primary_model: str = "claude-sonnet-4-6",
    ):
        self.primary_api_key = primary_api_key
        self.verifier_api_key = verifier_api_key
        self.nli_endpoint = nli_endpoint
        self.high_risk_flag_threshold = high_risk_flag_threshold
        self.verifier_model = verifier_model
        self.primary_model = primary_model
        self._enabled = bool(self.verifier_api_key)
        if not self._enabled:
            logger.info("L4-12 AdversarialLLMJury: verifier API key not set — jury DISABLED (degraded mode)")

    @classmethod
    def from_environment(cls) -> "AdversarialLLMJury":
        """
        Construct from environment variables. Mirrors MultiLLMClient.from_environment().
        
        Env vars:
          ANTHROPIC_API_KEY  — primary LLM (already used by MultiLLMClient)
          OPENAI_API_KEY     — verifier LLM (GPT-4o)
          CURANIQ_NLI_ENDPOINT — self-hosted NLI model (default: localhost:8100)
          CURANIQ_JURY_THRESHOLD — high-risk flag threshold (default: 0.30)
          CURANIQ_VERIFIER_MODEL — verifier model (default: gpt-4o)
        """
        import os
        return cls(
            primary_api_key=os.environ.get("ANTHROPIC_API_KEY"),
            verifier_api_key=os.environ.get("OPENAI_API_KEY"),
            nli_endpoint=os.environ.get("CURANIQ_NLI_ENDPOINT", "http://localhost:8100/entailment"),
            high_risk_flag_threshold=float(os.environ.get("CURANIQ_JURY_THRESHOLD", "0.30")),
            verifier_model=os.environ.get("CURANIQ_VERIFIER_MODEL", "gpt-4o"),
        )

    @property
    def is_enabled(self) -> bool:
        """True if verifier API key is configured and jury can run."""
        return self._enabled

    async def verify_claims(
        self,
        claims: list[AtomicClaim],
        evidence_pack: EvidencePack,
        query_risk_level: str = "standard",
    ) -> list[AtomicClaim]:
        """
        Run adversarial verification on all claims that have passed L4-3 initial checks.
        
        Only processes claims with PASS verdicts — already suppressed claims are skipped.
        Updates confidence scores and may suppress/flag additional claims.
        
        Returns updated claims list.
        """
        # If jury is disabled (no verifier API key), return claims with base confidence
        if not self._enabled:
            logger.info("L4-12 jury SKIPPED — no verifier API key. Claims proceed with base confidence.")
            return claims

        # Only verify claims that have initially passed L4-3
        claims_to_verify = [
            c for c in claims
            if c.verdict in (ClaimVerdict.PASS_HIGH, ClaimVerdict.PASS_MEDIUM, ClaimVerdict.PASS_LOW)
        ]
        
        if not claims_to_verify:
            return claims
        
        # Build verification payload for GPT-4o verifier
        evidence_context = self._build_evidence_context(claims_to_verify, evidence_pack)
        claims_json = self._build_claims_json(claims_to_verify)
        
        # Run GPT-4o verification
        verifier_results = await self._run_verifier(evidence_context, claims_json)
        
        # Process verifier results and update claims
        updated_claims = []
        flagged_high_risk_count = 0
        high_risk_total = 0
        
        for claim in claims:
            if claim.verdict not in (ClaimVerdict.PASS_HIGH, ClaimVerdict.PASS_MEDIUM, ClaimVerdict.PASS_LOW):
                updated_claims.append(claim)
                continue
            
            # Get verifier decision for this claim
            verifier_decision = verifier_results.get(claim.claim_id)
            
            if verifier_decision is None:
                # Verifier didn't return a result for this claim — conservative: treat as uncertain
                claim.verifier_decision = None
                updated_claims.append(claim)
                continue
            
            decision = verifier_decision.get("decision", "FAITHFUL")
            critique = verifier_decision.get("critique")
            
            claim.verifier_decision = VerifierDecision(decision.lower()) if decision.lower() in VerifierDecision._value2member_map_ else VerifierDecision.FAITHFUL
            claim.verifier_critique = critique
            claim.verifier_model = self.verifier_model
            
            if claim.is_high_risk:
                high_risk_total += 1
            
            if claim.verifier_decision != VerifierDecision.FAITHFUL:
                # Verifier flagged this claim — run NLI tie-breaker
                claim = await self._nli_tiebreaker(claim, evidence_pack)
                
                if claim.is_high_risk and claim.verdict != ClaimVerdict.PASS_HIGH:
                    flagged_high_risk_count += 1
            else:
                # Verifier agrees — claim is FAITHFUL
                # Boost confidence score: cross-LLM agreement = 1.0
                claim = self._update_confidence_for_agreement(claim, agreement_score=1.0)
            
            updated_claims.append(claim)
        
        # L4-12 Threshold check: >30% of high-risk claims flagged → REFUSE entire response
        if query_risk_level == "high_risk" and high_risk_total > 0:
            flag_rate = flagged_high_risk_count / high_risk_total
            if flag_rate > self.high_risk_flag_threshold:
                logger.warning(
                    f"L4-12 THRESHOLD EXCEEDED: {flag_rate:.0%} of high-risk claims flagged "
                    f"({flagged_high_risk_count}/{high_risk_total}). "
                    "Entire response will be REFUSED."
                )
                # Mark all remaining pass claims as refused
                for claim in updated_claims:
                    if claim.is_shown_to_clinician:
                        claim.verdict = ClaimVerdict.REFUSED
                        claim.verdict_reason = (
                            f"RESPONSE_REFUSED: {flag_rate:.0%} of high-risk claims in this "
                            "query were flagged by adversarial verification. "
                            "Escalated to human review queue (L10-5)."
                        )
        
        return updated_claims

    async def _run_verifier(
        self,
        evidence_context: str,
        claims_json: str,
    ) -> dict[str, dict]:
        """
        Call GPT-4o verifier to critique claims.
        Returns {claim_id: {decision, critique}}.
        
        On failure: returns empty dict (claims proceed with base confidence).
        """
        user_message = VERIFIER_USER_TEMPLATE.format(
            evidence_context=evidence_context,
            claims_json=claims_json,
        )
        
        try:
            async with aiohttp.ClientSession() as session:
                async with session.post(
                    "https://api.openai.com/v1/chat/completions",
                    headers={
                        "Authorization": f"Bearer {self.verifier_api_key}",
                        "Content-Type": "application/json",
                    },
                    json={
                        "model": self.verifier_model,
                        "messages": [
                            {"role": "system", "content": VERIFIER_SYSTEM_PROMPT},
                            {"role": "user", "content": user_message},
                        ],
                        "max_tokens": 2000,
                        "temperature": 0.0,  # Deterministic — we want consistency
                        "response_format": {"type": "json_object"},
                    },
                    timeout=aiohttp.ClientTimeout(total=30.0),
                ) as resp:
                    if resp.status != 200:
                        logger.warning(f"GPT-4o verifier returned HTTP {resp.status}")
                        return {}
                    
                    data = await resp.json()
                    content = data["choices"][0]["message"]["content"]
                    parsed = json.loads(content)
                    
                    # Convert to {claim_id: result} dict
                    verifications = parsed.get("verifications", [])
                    return {v["claim_id"]: v for v in verifications}
        
        except Exception as e:
            logger.error(f"GPT-4o verifier failed: {e}. Claims will proceed with base confidence.")
            return {}

    async def _nli_tiebreaker(
        self, claim: AtomicClaim, evidence_pack: EvidencePack
    ) -> AtomicClaim:
        """
        L4-12 Step 3: NLI tie-breaker when verifier has flagged a claim.
        
        (a) NLI agrees with verifier (low score) → claim SUPPRESSED
        (b) NLI agrees with primary (high score) → claim PASSES with uncertainty marker
        """
        chunk = evidence_pack.get_chunk(claim.evidence_binding.chunk_id)
        if not chunk:
            claim.verdict = ClaimVerdict.SUPPRESSED
            claim.verdict_reason = "NLI_TIEBREAK_FAIL: Evidence chunk not found for tie-breaking"
            return claim
        
        # Call NLI model
        try:
            async with aiohttp.ClientSession() as session:
                async with session.post(
                    self.nli_endpoint,
                    json={
                        "premise": chunk.content,
                        "hypothesis": claim.claim_text,
                    },
                    timeout=aiohttp.ClientTimeout(total=5.0),
                ) as resp:
                    if resp.status == 200:
                        result = await resp.json()
                        nli_score = float(result.get("entailment_score", 0.5))
                    else:
                        nli_score = 0.5  # Conservative
        except Exception:
            nli_score = 0.5  # Conservative on failure
        
        claim.tiebreak_nli_score = nli_score
        
        if nli_score >= 0.60:
            # NLI agrees with primary — claim passes but with uncertainty marker
            uncertainty = (
                f"⚠️ ADVERSARIAL FLAG: Verifier raised concern ({claim.verifier_decision.value}). "
                f"NLI tie-breaker supports claim (score: {nli_score:.2f}). "
                f"Verifier critique: {claim.verifier_critique or 'No detail'}"
            )
            claim.uncertainty_marker = uncertainty
            claim.human_review_flag = True
            
            # Reduce confidence to MEDIUM at best
            new_confidence = min(claim.confidence_score or 0.85, 0.80)
            claim = self._update_confidence_for_agreement(claim, agreement_score=0.5)
            claim.verdict = ClaimVerdict.PASS_MEDIUM
            claim.verdict_reason = "VERIFIER_FLAGGED_BUT_NLI_PASSES"
        
        else:
            # NLI agrees with verifier — suppress claim
            claim.verdict = ClaimVerdict.SUPPRESSED
            claim.verdict_reason = (
                f"ADVERSARIAL_SUPPRESS: Verifier flagged ({claim.verifier_decision.value}) "
                f"and NLI tie-breaker agrees (score: {nli_score:.2f} < 0.60). "
                f"Claim suppressed. Critique: {claim.verifier_critique or 'None'}"
            )
        
        return claim

    def _update_confidence_for_agreement(
        self, claim: AtomicClaim, agreement_score: float
    ) -> AtomicClaim:
        """
        Update confidence score with actual cross-LLM agreement score from L4-12.
        
        Agreement score:
        1.0 = verifier says FAITHFUL (both models agree)
        0.5 = verifier flagged but NLI passes (disagreement)
        0.0 = both verifier and NLI flag (all models disagree)
        """
        if claim.confidence_components is None:
            claim.confidence_components = {}
        
        claim.confidence_components["cross_llm_agreement"] = agreement_score
        
        # Recompute confidence with actual agreement score
        weights = {
            "nli": 0.35,
            "llm_agreement": 0.20,
            "evidence_tier": 0.20,
            "recency": 0.15,
            "source_count": 0.10,
        }
        
        score = (
            weights["nli"] * (claim.nli_entailment_score or 0.5) +
            weights["llm_agreement"] * agreement_score +
            weights["evidence_tier"] * claim.confidence_components.get("evidence_tier", 0.7) +
            weights["recency"] * claim.confidence_components.get("recency", 0.85) +
            weights["source_count"] * claim.confidence_components.get("source_count", 0.6)
        )
        
        claim.confidence_score = round(max(0.0, min(1.0, score)), 4)
        
        # Re-assign verdict based on updated confidence
        if claim.confidence_score >= 0.85:
            claim.verdict = ClaimVerdict.PASS_HIGH
        elif claim.confidence_score >= 0.70:
            claim.verdict = ClaimVerdict.PASS_MEDIUM
        elif claim.confidence_score >= 0.50:
            claim.verdict = ClaimVerdict.PASS_LOW
            claim.human_review_flag = True
        else:
            claim.verdict = ClaimVerdict.SUPPRESSED
        
        return claim

    def _build_evidence_context(
        self, claims: list[AtomicClaim], evidence_pack: EvidencePack
    ) -> str:
        """Build evidence context for the verifier — only chunks referenced by passing claims."""
        seen_ids = set()
        lines = []
        
        for claim in claims:
            chunk_id = claim.evidence_binding.chunk_id
            if chunk_id in seen_ids:
                continue
            seen_ids.add(chunk_id)
            
            chunk = evidence_pack.get_chunk(chunk_id)
            if chunk:
                lines.append(f"[EVIDENCE_ID: {chunk_id}]")
                lines.append(f"Source: {chunk.provenance.source_api.value}")
                lines.append(f"Evidence tier: {chunk.evidence_tier.value}")
                lines.append(f"Content: {chunk.content[:600]}")
                lines.append("")
        
        return "\n".join(lines)

    def _build_claims_json(self, claims: list[AtomicClaim]) -> str:
        """Format claims for verifier consumption."""
        claims_data = [
            {
                "claim_id": claim.claim_id,
                "claim_text": claim.claim_text,
                "claim_type": claim.claim_type.value,
                "evidence_id": claim.evidence_binding.chunk_id,
            }
            for claim in claims
        ]
        return json.dumps(claims_data, indent=2)


# ─────────────────────────────────────────────────────────────────────────────
# CONFIDENCE SCORER — L4-13
# Full composite confidence scoring after adversarial verification
# ─────────────────────────────────────────────────────────────────────────────

class ConfidenceScorer:
    """
    L4-13: Confidence Scoring & Uncertainty Quantifier.
    
    'Every clinical claim receives a composite confidence score displayed
    to the clinician.'
    
    Score = weighted average of 5 components (per architecture):
    (a) NLI entailment score from self-hosted model (0.0-1.0)
    (b) Cross-LLM agreement from L4-12 (1.0=agree, 0.5=flagged, 0.0=all disagree)
    (c) Evidence quality tier per Oxford CEBM levels
    (d) Evidence recency
    (e) Source count
    
    Thresholds:
    ≥0.85 → HIGH — shown normally
    0.70-0.85 → MEDIUM — shown with uncertainty marker
    0.50-0.70 → LOW — shown with caveat + human review flag
    <0.50 → SUPPRESS — never shown to clinician
    """

    # Oxford CEBM evidence quality scores (L4-13 formula)
    CEBM_SCORES = {
        "systematic_review": 1.0,
        "rct": 0.9,
        "guideline": 0.85,
        "cohort": 0.7,
        "case_report": 0.5,
        "expert_opinion": 0.3,
        "preprint": 0.0,
        "unknown": 0.0,
    }

    # Recency scores (publication age)
    # <1yr = 1.0, 1-3yr = 0.85, 3-5yr = 0.7, >5yr = 0.5
    
    # Component weights (must sum to 1.0)
    WEIGHTS = {
        "nli_entailment":    0.35,
        "cross_llm_agreement": 0.20,
        "evidence_quality":  0.20,
        "recency":           0.15,
        "source_count":      0.10,
    }

    def score_claim(
        self,
        claim: AtomicClaim,
        evidence_chunk: EvidenceChunk,
        cross_llm_agreement: float = 0.5,
        source_count: int = 1,
    ) -> AtomicClaim:
        """
        Compute final confidence score for a claim.
        Called after adversarial verification (L4-12) completes.
        
        Returns updated AtomicClaim with final score and verdict.
        """
        # Component (a): NLI entailment
        nli_score = claim.nli_entailment_score or 0.5
        
        # Component (b): Cross-LLM agreement
        llm_agreement = cross_llm_agreement
        
        # Component (c): Evidence quality (CEBM tier)
        evidence_quality = evidence_chunk.cebm_score()
        
        # Component (d): Recency
        recency = evidence_chunk.compute_recency_score()
        
        # Component (e): Source count
        if source_count == 0:
            source_score = 0.0  # No evidence → SUPPRESS
        elif source_count >= 3:
            source_score = 1.0
        elif source_count == 2:
            source_score = 0.8
        else:
            source_score = 0.6
        
        # Composite score
        composite = (
            self.WEIGHTS["nli_entailment"]     * nli_score +
            self.WEIGHTS["cross_llm_agreement"] * llm_agreement +
            self.WEIGHTS["evidence_quality"]   * evidence_quality +
            self.WEIGHTS["recency"]            * recency +
            self.WEIGHTS["source_count"]       * source_score
        )
        composite = round(max(0.0, min(1.0, composite)), 4)
        
        # Build component breakdown for transparency
        claim.confidence_score = composite
        claim.confidence_components = {
            "nli_entailment": round(nli_score, 4),
            "cross_llm_agreement": round(llm_agreement, 4),
            "evidence_quality": round(evidence_quality, 4),
            "recency": round(recency, 4),
            "source_count_score": round(source_score, 4),
            "source_count": source_count,
            "evidence_tier": evidence_chunk.evidence_tier.value,
            "source_api": evidence_chunk.provenance.source_api.value,
            "evidence_tier_label": (
                f"{source_count} source(s) [{evidence_chunk.evidence_tier.value} from "
                f"{evidence_chunk.provenance.source_api.value}]"
            ),
        }
        
        # Assign verdict + clinical display
        claim = self._assign_final_verdict(claim, composite)
        
        return claim

    def score_multi_source_claim(
        self,
        claim: AtomicClaim,
        evidence_chunks: list[EvidenceChunk],
        cross_llm_agreement: float = 0.5,
    ) -> AtomicClaim:
        """
        Score a claim supported by multiple evidence sources.
        
        Per architecture: '3+ independent sources = 1.0' for source_count component.
        When multiple chunks support the same claim, use the best CEBM tier
        and average recency.
        """
        if not evidence_chunks:
            claim.confidence_score = 0.0
            claim.verdict = ClaimVerdict.SUPPRESSED
            claim.verdict_reason = "No evidence sources available"
            return claim
        
        # Best evidence quality (highest CEBM tier)
        best_quality = max(c.cebm_score() for c in evidence_chunks)
        
        # Average recency across sources
        avg_recency = sum(c.compute_recency_score() for c in evidence_chunks) / len(evidence_chunks)
        
        # Source count benefit
        source_count = len(evidence_chunks)
        
        # Use the primary chunk for NLI score (already computed)
        nli_score = claim.nli_entailment_score or 0.5
        
        source_score = 1.0 if source_count >= 3 else (0.8 if source_count == 2 else 0.6)
        
        composite = (
            self.WEIGHTS["nli_entailment"]     * nli_score +
            self.WEIGHTS["cross_llm_agreement"] * cross_llm_agreement +
            self.WEIGHTS["evidence_quality"]   * best_quality +
            self.WEIGHTS["recency"]            * avg_recency +
            self.WEIGHTS["source_count"]       * source_score
        )
        composite = round(max(0.0, min(1.0, composite)), 4)
        
        best_chunk = max(evidence_chunks, key=lambda c: c.cebm_score())
        
        claim.confidence_score = composite
        claim.confidence_components = {
            "nli_entailment": round(nli_score, 4),
            "cross_llm_agreement": round(cross_llm_agreement, 4),
            "evidence_quality": round(best_quality, 4),
            "recency": round(avg_recency, 4),
            "source_count_score": round(source_score, 4),
            "source_count": source_count,
            "evidence_tier": best_chunk.evidence_tier.value,
            "evidence_tier_label": (
                f"{source_count} independent source(s) "
                f"[best: {best_chunk.evidence_tier.value} from {best_chunk.provenance.source_api.value}]"
            ),
        }
        
        claim = self._assign_final_verdict(claim, composite)
        return claim

    def _assign_final_verdict(self, claim: AtomicClaim, score: float) -> AtomicClaim:
        """
        Assign final verdict per L4-13 thresholds.
        Also generates the clinician-facing confidence display string.
        """
        components = claim.confidence_components or {}
        tier_label = components.get("evidence_tier_label", "clinical evidence")
        
        if score >= 0.85:
            claim.verdict = ClaimVerdict.PASS_HIGH
            claim.verdict_reason = "HIGH_CONFIDENCE"
            claim.uncertainty_marker = None
            claim.human_review_flag = False
        
        elif score >= 0.70:
            claim.verdict = ClaimVerdict.PASS_MEDIUM
            claim.verdict_reason = "MEDIUM_CONFIDENCE"
            claim.uncertainty_marker = (
                f"⚠️ Moderate confidence ({score:.2f}). "
                "Evidence supports this claim but quality/recency warrants verification."
            )
            claim.human_review_flag = False
        
        elif score >= 0.50:
            claim.verdict = ClaimVerdict.PASS_LOW
            claim.verdict_reason = "LOW_CONFIDENCE"
            claim.uncertainty_marker = (
                f"⚠️ Low confidence ({score:.2f}). "
                "Limited or older evidence. Consult current guidelines before acting."
            )
            claim.human_review_flag = True
        
        else:
            claim.verdict = ClaimVerdict.SUPPRESSED
            claim.verdict_reason = (
                f"SUPPRESSED: Confidence {score:.3f} below 0.50 threshold. "
                "Insufficient evidence quality to support this clinical claim."
            )
            claim.uncertainty_marker = None
            claim.human_review_flag = False
        
        return claim

    def format_confidence_display(self, claim: AtomicClaim) -> str:
        """
        Human-readable confidence display for the clinician UI.
        
        Per architecture example:
        'Confidence: HIGH (0.91) — based on 2 systematic reviews + FDA label + KDIGO guideline'
        """
        if claim.confidence_score is None:
            return "Confidence: UNSCORED"
        
        score = claim.confidence_score
        components = claim.confidence_components or {}
        
        if score >= 0.85:
            level = "HIGH"
        elif score >= 0.70:
            level = "MEDIUM"
        elif score >= 0.50:
            level = "LOW"
        else:
            return f"Confidence: SUPPRESSED ({score:.2f})"
        
        evidence_basis = components.get("evidence_tier_label", "clinical evidence")
        
        return f"Confidence: {level} ({score:.2f}) — based on {evidence_basis}"

    def generate_uncertainty_notice(
        self, claim: AtomicClaim, include_components: bool = False
    ) -> Optional[str]:
        """
        Generate uncertainty notice for medium/low confidence claims.
        These are shown alongside the claim to the clinician.
        """
        if claim.verdict == ClaimVerdict.PASS_HIGH:
            return None
        
        if claim.verdict == ClaimVerdict.PASS_MEDIUM:
            notice = (
                f"EVIDENCE NOTE: This claim is based on {claim.confidence_components.get('evidence_tier_label', 'limited evidence')}. "
                "Confidence: MODERATE. Recommend verifying with current guideline or drug label."
            )
        elif claim.verdict == ClaimVerdict.PASS_LOW:
            notice = (
                f"⚠️ EVIDENCE CAUTION: Low confidence ({claim.confidence_score:.2f}). "
                "Evidence is limited, outdated, or has conflicting adversarial verification. "
                "This claim requires clinical judgment and verification from primary sources. "
                "Flagged for human review."
            )
        else:
            return None
        
        if include_components and claim.confidence_components:
            c = claim.confidence_components
            breakdown = (
                f"\nScore breakdown: NLI={c.get('nli_entailment', 'N/A'):.2f}, "
                f"Cross-LLM={c.get('cross_llm_agreement', 'N/A'):.2f}, "
                f"Evidence quality={c.get('evidence_quality', 'N/A'):.2f}, "
                f"Recency={c.get('recency', 'N/A'):.2f}, "
                f"Source count={c.get('source_count', 'N/A')}"
            )
            notice += breakdown
        
        return notice
