"""Initial schema with audit unique constraint

Revision ID: 8bb2411b4b3f
Revises: 
Create Date: 2026-04-25 10:07:14.328235
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
import curaniq.db.models


revision: str = '8bb2411b4b3f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sources',
    sa.Column('id', curaniq.db.models.UUIDType(), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('authority_level', sa.Integer(), nullable=False),
    sa.Column('jurisdictions', sa.String(length=200), nullable=False),
    sa.Column('base_url', sa.String(length=500), nullable=True),
    sa.Column('license_status', sa.String(length=40), nullable=False),
    sa.Column('license_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ttl_seconds', sa.Integer(), nullable=False),
    sa.Column('fail_closed_high_risk', sa.Boolean(), nullable=False),
    sa.Column('allowed_claim_types', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('last_successful_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_attempted_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('ttl_seconds > 0', name='ck_source_ttl_positive'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_type')
    )
    op.create_index('ix_sources_status', 'sources', ['status'], unique=False)
    op.create_table('tenants',
    sa.Column('id', curaniq.db.models.UUIDType(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('jurisdiction', sa.String(length=10), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('runtime_mode', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('audit_chain_heads',
    sa.Column('tenant_id', curaniq.db.models.UUIDType(), nullable=False),
    sa.Column('head_event_id', curaniq.db.models.UUIDType(), nullable=True),
    sa.Column('head_chain_hash', sa.String(length=64), nullable=False),
    sa.Column('head_sequence', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tenant_id')
    )
    op.create_table('evidence_objects',
    sa.Column('id', curaniq.db.models.UUIDType(), nullable=False),
    sa.Column('source_id', curaniq.db.models.UUIDType(), nullable=False),
    sa.Column('external_id', sa.String(length=200), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('snippet', sa.Text(), nullable=False),
    sa.Column('snippet_hash', sa.String(length=64), nullable=False),
    sa.Column('snippet_byte_offset', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(length=1000), nullable=True),
    sa.Column('doi', sa.String(length=200), nullable=True),
    sa.Column('authors', sa.Text(), nullable=True),
    sa.Column('tier', sa.String(length=40), nullable=False),
    sa.Column('grade', sa.String(length=10), nullable=True),
    sa.Column('jurisdiction', sa.String(length=10), nullable=False),
    sa.Column('published_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_last_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_version', sa.String(length=50), nullable=True),
    sa.Column('license_status', sa.String(length=40), nullable=False),
    sa.Column('is_retracted', sa.Boolean(), nullable=False),
    sa.Column('retraction_notice', sa.Text(), nullable=True),
    sa.Column('is_superseded', sa.Boolean(), nullable=False),
    sa.Column('superseded_by_id', curaniq.db.models.UUIDType(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('staleness_ttl_hours', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['superseded_by_id'], ['evidence_objects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'external_id', 'version', name='uq_evidence_source_extid_ver')
    )
    op.create_index('ix_evidence_jurisdiction', 'evidence_objects', ['jurisdiction'], unique=False)
    op.create_index('ix_evidence_published', 'evidence_objects', ['published_date'], unique=False)
    op.create_index('ix_evidence_retracted', 'evidence_objects', ['is_retracted'], unique=False)
    op.create_index('ix_evidence_source_external', 'evidence_objects', ['source_id', 'external_id'], unique=False)
    op.create_table('source_sync_runs',
    sa.Column('id', curaniq.db.models.UUIDType(), nullable=False),
    sa.Column('source_id', curaniq.db.models.UUIDType(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('outcome', sa.String(length=20), nullable=False),
    sa.Column('items_fetched', sa.Integer(), nullable=False),
    sa.Column('items_new', sa.Integer(), nullable=False),
    sa.Column('items_updated', sa.Integer(), nullable=False),
    sa.Column('items_superseded', sa.Integer(), nullable=False),
    sa.Column('error_class', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sync_runs_outcome', 'source_sync_runs', ['outcome'], unique=False)
    op.create_index('ix_sync_runs_source_started', 'source_sync_runs', ['source_id', 'started_at'], unique=False)
    op.create_table('source_versions',
    sa.Column('id', curaniq.db.models.UUIDType(), nullable=False),
    sa.Column('source_id', curaniq.db.models.UUIDType(), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('license_terms_hash', sa.String(length=64), nullable=True),
    sa.Column('config_json', sa.Text(), nullable=True),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deactivated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'version', name='uq_source_version')
    )
    op.create_index('ix_source_versions_source_active', 'source_versions', ['source_id', 'is_current'], unique=False)
    op.create_table('users',
    sa.Column('id', curaniq.db.models.UUIDType(), nullable=False),
    sa.Column('tenant_id', curaniq.db.models.UUIDType(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=40), nullable=False),
    sa.Column('license_number', sa.String(length=100), nullable=True),
    sa.Column('license_jurisdiction', sa.String(length=10), nullable=True),
    sa.Column('license_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('mfa_enabled', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_users_tenant_email', 'users', ['tenant_id', 'email'], unique=True)
    op.create_table('audit_events',
    sa.Column('id', curaniq.db.models.UUIDType(), nullable=False),
    sa.Column('tenant_id', curaniq.db.models.UUIDType(), nullable=True),
    sa.Column('user_id', curaniq.db.models.UUIDType(), nullable=True),
    sa.Column('query_id', curaniq.db.models.UUIDType(), nullable=True),
    sa.Column('event_type', sa.String(length=40), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('payload_hash', sa.String(length=64), nullable=False),
    sa.Column('prev_chain_hash', sa.String(length=64), nullable=False),
    sa.Column('chain_hash', sa.String(length=64), nullable=False),
    sa.Column('model_id', sa.String(length=100), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('pipeline_version', sa.String(length=50), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'sequence', name='uq_audit_tenant_sequence')
    )
    op.create_index('ix_audit_event_type', 'audit_events', ['event_type'], unique=False)
    op.create_index('ix_audit_query', 'audit_events', ['query_id'], unique=False)
    op.create_index('ix_audit_tenant_created', 'audit_events', ['tenant_id', 'created_at'], unique=False)
    op.create_table('evidence_versions',
    sa.Column('id', curaniq.db.models.UUIDType(), nullable=False),
    sa.Column('evidence_object_id', curaniq.db.models.UUIDType(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('change_type', sa.String(length=40), nullable=False),
    sa.Column('previous_snippet_hash', sa.String(length=64), nullable=True),
    sa.Column('new_snippet_hash', sa.String(length=64), nullable=True),
    sa.Column('diff_summary', sa.Text(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['evidence_object_id'], ['evidence_objects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ev_versions_obj_recorded', 'evidence_versions', ['evidence_object_id', 'recorded_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ev_versions_obj_recorded', table_name='evidence_versions')
    op.drop_table('evidence_versions')
    op.drop_index('ix_audit_tenant_created', table_name='audit_events')
    op.drop_index('ix_audit_query', table_name='audit_events')
    op.drop_index('ix_audit_event_type', table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index('ix_users_tenant_email', table_name='users')
    op.drop_table('users')
    op.drop_index('ix_source_versions_source_active', table_name='source_versions')
    op.drop_table('source_versions')
    op.drop_index('ix_sync_runs_source_started', table_name='source_sync_runs')
    op.drop_index('ix_sync_runs_outcome', table_name='source_sync_runs')
    op.drop_table('source_sync_runs')
    op.drop_index('ix_evidence_source_external', table_name='evidence_objects')
    op.drop_index('ix_evidence_retracted', table_name='evidence_objects')
    op.drop_index('ix_evidence_published', table_name='evidence_objects')
    op.drop_index('ix_evidence_jurisdiction', table_name='evidence_objects')
    op.drop_table('evidence_objects')
    op.drop_table('audit_chain_heads')
    op.drop_table('tenants')
    op.drop_index('ix_sources_status', table_name='sources')
    op.drop_table('sources')
    # ### end Alembic commands ###
